eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/ # Eureka 1 registers to Eureka 2
#      defaultZone: http://localhost:8761/eureka/ # Eureka 2 registers to Eureka 1
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
#server:
#  port: 8761
